In [5]:
import torch
import numpy as np

### The tensor is a multi dimensional matrix with elements of a Single data type

Like a numpy array but works better on GPU 

# Lists

In [3]:
list = [[1,2,6,78,123,4],[1,2,3]]
list

# multi dimension and different kinds of data on a list

[[1, 2, 6, 78, 123, 4], [1, 2, 3]]

# Numpy Arrays

In [6]:
np1 = np.random.rand(3,4) # 3 lines 4 columns
np1

# Same kind of type on every element
# Deals better with math

array([[0.47159984, 0.25389698, 0.74316216, 0.34781956],
       [0.35607372, 0.81309521, 0.62539399, 0.3917569 ],
       [0.72006456, 0.35706543, 0.11311479, 0.04453649]])

In [7]:
np1.dtype

dtype('float64')

# Tensors

In [8]:
tensor = torch.randn(3,4) # 3 lines and 4 columns of random data
tensor

tensor([[ 1.4573, -0.3534, -2.1680,  1.8890],
        [ 0.7507, -0.4695,  0.6672, -0.1959],
        [-0.8456,  0.7690, -0.7894, -0.2694]])

In [10]:
# From numpy

new_tensor = torch.tensor(np1)
new_tensor.dtype

torch.float64

# Operations

In [16]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# reshape and view
reshape = my_torch.reshape(2,5)
reshape

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [23]:
# If i don't know the number of items

my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
reshape2 = my_torch2.reshape(3,-1)
reshape2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [25]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [30]:
# They will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [35]:
my_torch5[3] = 100
my_torch5

tensor([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9])

In [36]:
my_torch6
# It was updated !!!

tensor([[  0,   1,   2, 100,   4],
        [  5,   6,   7,   8,   9]])

In [37]:
# Slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
my_torch7[3:]

tensor([3, 4, 5, 6, 7, 8, 9])

# Math

In [44]:
tensor_a = torch.tensor([1,3,4,4,5])
tensor_b = torch.tensor([1,0,-1,3,4])

In [47]:
# Add and subtraction
sum = tensor_a + tensor_b
sub = tensor_a - tensor_b

print(f"Sum {sum} and sub {sub}")

Sum tensor([2, 3, 3, 7, 9]) and sub tensor([0, 3, 5, 1, 1])


In [50]:
# Add longhand -> I can call a function
sum = torch.add(tensor_a,tensor_b)
sub = torch.sub(tensor_a,tensor_b)
print(f"Sum {sum} and sub {sub}")

Sum tensor([2, 3, 3, 7, 9]) and sub tensor([0, 3, 5, 1, 1])


In [51]:
# Multiplication
tensor_a*tensor_b
# or just torch.mul(tensor_a,tensor_b)

tensor([ 1,  0, -4, 12, 20])

In [53]:
# Division
tensor_a/tensor_b 
# convert to a float 
# And since there is a zero , the value explode to inf

# i could also make torch.div(tensor_a,tensor_b)

tensor([ 1.0000,     inf, -4.0000,  1.3333,  1.2500])

In [55]:
# Remainder Modulus
tensor_b % tensor_a

# Remainder longhand could be
# torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 3, 3, 4])

In [56]:
# Exponents

torch.pow(tensor_a,tensor_b)
# could also make tensor_a**tensor_b

tensor([  1,   1,   0,  64, 625])

In [57]:
# i can also call like this
tensor_a.add(tensor_b)

tensor([2, 3, 3, 7, 9])

In [58]:
# Reassignment
#tensor_a = tensor_a + tensor_b 

tensor_a.add_(tensor_b)

tensor([2, 3, 3, 7, 9])

In [59]:
tensor_a

tensor([2, 3, 3, 7, 9])

# Neural Network